export const wisconsinSections = [
  {
    id: 1,
    type: "instruction",
    instructions: [
      "Vamos a completar dos tareas de correspondencias. Para ambas tareas, hay que unir dos cartas según su color o forma de la imagen.",
      "Para unir las cartas, se utilizan las teclas 'A', y la tecla 'L'. Si aprietas la tecla 'A' la carta irá a la izquierda, y si aprietas la 'L' irá a la derecha.",
      "Puedes tener sus dedos encima de las teclas para poder responder lo más rápido posible. Se requiere menos de 5 minutos para completar ambas tareas.",
    ],
    specialMessage:
      "Cuándo el participante esté listo, toca la 'N' para continuar.",
  },
  {
    id: 2,
    type: "cards",
    cardOneSrc: "/images/wisconsin_face.png",
    cardTwoSrc: "/images/wisconsin_face.png",
    cardThreeSrc: "/images/wisconsin_face.png",
    top: -295,
    left: -252,
    right: 0,
    messages: [
      "Ahora vamos a practicar con las teclas que vamos a usar. ¿Puedes tocar la tecla A?",
    ],
    errorMessages: [
      "Lo siento, esa no fue la correcta. Recuerda, solo tienes que tocar la tecla indicada. Intentamos denuevo.",
    ],
    successMessages: ["Muy bien, tocaste la A."],
    correctAnswer: "a",
    tutorial: true,
  },
  {
    id: 3,
    type: "cards",
    cardOneSrc: "/images/wisconsin_face.png",
    cardTwoSrc: "/images/wisconsin_face.png",
    cardThreeSrc: "/images/wisconsin_face.png",
    top: -295,
    left: 0,
    right: -252,
    messages: ["¿Puedes tocar la tecla L?"],
    errorMessages: [
      "Lo siento, esa no fue la correcta. Recuerda, solo tienes que tocar la tecla indicada. Intentamos denuevo.",
    ],
    successMessages: ["Muy bien, tocaste la L."],
    correctAnswer: "l",
    tutorial: true,
  },
  {
    id: 4,
    type: "cards",
    cardOneSrc: "/images/wisconsin_tren_rojo.png",
    cardTwoSrc: "/images/wisconsin_estrella_azul.png",
    cardThreeSrc: "/images/wisconsin_tren_azul.png",
    top: -286.52,
    left: -252.9,
    right: 0,
    messages: [],
    errorMessages: [],
    successMessages: [],
    correctAnswer: "a",
    tutorial: true,
  },
  {
    id: 5,
    type: "cards",
    cardOneSrc: "/images/wisconsin_tren_rojo.png",
    cardTwoSrc: "/images/wisconsin_estrella_azul.png",
    cardThreeSrc: "/images/wisconsin_estrella_roja.png",
    top: -287.2,
    left: 0,
    right: -248,
    messages: [],
    errorMessages: [],
    successMessages: [],
    correctAnswer: "l",
    tutorial: true,
  },
  {
    id: 6,
    type: "instruction",
    instructions: [
      "¡Muy bien! Ahora, vamos a empezar. Trata de ir rápido, ordenando las cartas correctamente.",
    ],
    specialMessage:
      "Cuándo el participante esté listo, toca la 'N' para continuar.",
  },
];
