export const wisconsinSections = [
  {
    id: 1,
    type: "instruction",
    instructions: [
      "Vamos a completar tres tareas de correspondencias. Usted deberá ordenar las cartas por su color, forma o según el número de imágenes que aparecen.",
      "Para unir las cartas, se utilizan las teclas 'A', y la tecla 'L'. Si aprietas la tecla 'A' la carta irá a la izquierda, y si aprietas la 'L' irá a la derecha.",
      "Puedes tener sus dedos encima de las teclas para poder responder lo más rápido posible. Se requiere menos de 5 minutos para completar ambas tareas.",
    ],
    specialMessage:
      "Cuándo el participante esté listo, toca la 'N' para continuar.",
  },
  {
    id: 2,
    type: "cards",
    cardOneSrc: "/images/wisconsin_tren_rojo.png",
    cardTwoSrc: "/images/wisconsin_estrella_azul.png",
    cardThreeSrc: "/images/wisconsin_tren_azul.png",
    top: -286.52,
    left: -252.9,
    right: -248,
    messages: [],
    errorMessages: [],
    successMessages: [],
    correctAnswer: "a",
    tutorial: false,
    item_id: null,
    answer: null,
    time: null,
  },
  {
    id: 3,
    type: "cards",
    cardOneSrc: "/images/wisconsin_tren_rojo.png",
    cardTwoSrc: "/images/wisconsin_estrella_azul.png",
    cardThreeSrc: "/images/wisconsin_estrella_roja.png",
    top: -286.52,
    left: -252.9,
    right: -248,
    messages: [],
    errorMessages: [],
    successMessages: [],
    correctAnswer: "l",
    tutorial: false,
    item_id: null,
    answer: null,
    time: null,
  },
  {
    id: 4,
    type: "cards",
    cardOneSrc: "/images/wisconsin_tren_rojo.png",
    cardTwoSrc: "/images/wisconsin_estrella_azul.png",
    cardThreeSrc: "/images/wisconsin_estrella_roja.png",
    top: -286.52,
    left: -252.9,
    right: -248,
    messages: [],
    errorMessages: [],
    successMessages: [],
    correctAnswer: "l",
    tutorial: false,
    item_id: null,
    answer: null,
    time: null,
  },
  {
    id: 5,
    type: "cards",
    cardOneSrc: "/images/wisconsin_tren_rojo.png",
    cardTwoSrc: "/images/wisconsin_estrella_azul.png",
    cardThreeSrc: "/images/wisconsin_tren_azul.png",
    top: -286.52,
    left: -252.9,
    right: -248,
    messages: [],
    errorMessages: [],
    successMessages: [],
    correctAnswer: "a",
    tutorial: false,
    item_id: null,
    answer: null,
    time: null,
  },
  {
    id: 6,
    type: "cards",
    cardOneSrc: "/images/wisconsin_tren_rojo.png",
    cardTwoSrc: "/images/wisconsin_estrella_azul.png",
    cardThreeSrc: "/images/wisconsin_tren_azul.png",
    top: -286.52,
    left: -252.9,
    right: -248,
    messages: [],
    errorMessages: [],
    successMessages: [],
    correctAnswer: "a",
    tutorial: false,
    item_id: null,
    answer: null,
    time: null,
  },
  {
    id: 7,
    type: "cards",
    cardOneSrc: "/images/wisconsin_tren_rojo.png",
    cardTwoSrc: "/images/wisconsin_estrella_azul.png",
    cardThreeSrc: "/images/wisconsin_estrella_roja.png",
    top: -286.52,
    left: -252.9,
    right: -248,
    messages: [],
    errorMessages: [],
    successMessages: [],
    correctAnswer: "l",
    tutorial: false,
    item_id: null,
    answer: null,
    time: null,
  },
  {
    id: 8,
    type: "cards",
    cardOneSrc: "/images/wisconsin_tren_rojo.png",
    cardTwoSrc: "/images/wisconsin_estrella_azul.png",
    cardThreeSrc: "/images/wisconsin_tren_azul.png",
    top: -286.52,
    left: -252.9,
    right: -248,
    messages: [],
    errorMessages: [],
    successMessages: [],
    correctAnswer: "a",
    tutorial: false,
    item_id: null,
    answer: null,
    time: null,
  },
  {
    id: 9,
    type: "cards",
    cardOneSrc: "/images/wisconsin_tren_rojo.png",
    cardTwoSrc: "/images/wisconsin_estrella_azul.png",
    cardThreeSrc: "/images/wisconsin_estrella_roja.png",
    top: -286.52,
    left: -252.9,
    right: -248,
    messages: [],
    errorMessages: [],
    successMessages: [],
    correctAnswer: "l",
    tutorial: false,
    item_id: null,
    answer: null,
    time: null,
  },
  {
    id: 10,
    type: "cards",
    cardOneSrc: "/images/wisconsin_tren_rojo.png",
    cardTwoSrc: "/images/wisconsin_estrella_azul.png",
    cardThreeSrc: "/images/wisconsin_estrella_roja.png",
    top: -286.52,
    left: -252.9,
    right: -248,
    messages: [],
    errorMessages: [],
    successMessages: [],
    correctAnswer: "l",
    tutorial: false,
    item_id: null,
    answer: null,
    time: null,
  },
  {
    id: 11,
    type: "cards",
    cardOneSrc: "/images/wisconsin_tren_rojo.png",
    cardTwoSrc: "/images/wisconsin_estrella_azul.png",
    cardThreeSrc: "/images/wisconsin_tren_azul.png",
    top: -286.52,
    left: -252.9,
    right: -248,
    messages: [],
    errorMessages: [],
    successMessages: [],
    correctAnswer: "a",
    tutorial: false,
    item_id: null,
    answer: null,
    time: null,
  },
  {
    id: 12,
    type: "cards",
    cardOneSrc: "/images/wisconsin_tren_rojo.png",
    cardTwoSrc: "/images/wisconsin_estrella_azul.png",
    cardThreeSrc: "/images/wisconsin_tren_azul.png",
    top: -286.52,
    left: -252.9,
    right: -248,
    messages: [],
    errorMessages: [],
    successMessages: [],
    correctAnswer: "a",
    tutorial: false,
    item_id: null,
    answer: null,
    time: null,
  },
  {
    id: 13,
    type: "cards",
    cardOneSrc: "/images/wisconsin_tren_rojo.png",
    cardTwoSrc: "/images/wisconsin_estrella_azul.png",
    cardThreeSrc: "/images/wisconsin_estrella_roja.png",
    top: -286.52,
    left: -252.9,
    right: -248,
    messages: [],
    errorMessages: [],
    successMessages: [],
    correctAnswer: "l",
    tutorial: false,
    item_id: null,
    answer: null,
    time: null,
  },
  {
    id: 14,
    type: "instruction",
    instructions: ["Muy bien 😀"],
    specialMessage: "Toca la 'N' para continuar.",
  },
  {
    id: 20,
    type: "cards",
    cardOneSrc: "/images/wisconsin_tren_rojo.png",
    cardTwoSrc: "/images/wisconsin_estrella_azul.png",
    cardThreeSrc: "/images/wisconsin_estrella_roja.png",
    top: -286.52,
    left: -252.9,
    right: -248,
    messages: [
      "Muy bien, ahora vamos a ordenar las cartas según su color",
      "Selecciona la carta que corresponde según su color.",
    ],
    errorMessages: [
      "Lo siento, esa no fue la correcta. Recuerda, tienes que unir las cartas con el mismo color. Intentemos de nuevo.",
    ],
    successMessages: [
      "Muy bien, la carta de la estrella roja va con la carta del tren rojo.",
    ],
    correctAnswer: "a",
    tutorial: true,
  },
  {
    id: 21,
    type: "cards",
    cardOneSrc: "/images/wisconsin_tren_rojo.png",
    cardTwoSrc: "/images/wisconsin_estrella_azul.png",
    cardThreeSrc: "/images/wisconsin_tren_azul.png",
    top: -286.52,
    left: -252.9,
    right: -248,
    messages: ["Selecciona la carta que corresponde según su color."],
    errorMessages: [
      "Lo siento, esa no fue la correcta. Recuerda, tienes que unir las cartas con el mismo color. Intentemos de nuevo.",
    ],
    successMessages: [
      "Muy bien, la carta del tren azul va con la carta de la estrella azul.",
    ],
    correctAnswer: "l",
    tutorial: true,
  },
  {
    id: 22,
    type: "cards",
    cardOneSrc: "/images/wisconsin_tren_rojo.png",
    cardTwoSrc: "/images/wisconsin_estrella_azul.png",
    cardThreeSrc: "/images/wisconsin_estrella_roja.png",
    top: -286.52,
    left: -252.9,
    right: -248,
    messages: [],
    errorMessages: [],
    successMessages: [],
    correctAnswer: "a",
    tutorial: false,
    item_id: null,
    answer: null,
    time: null,
  },
  {
    id: 23,
    type: "cards",
    cardOneSrc: "/images/wisconsin_tren_rojo.png",
    cardTwoSrc: "/images/wisconsin_estrella_azul.png",
    cardThreeSrc: "/images/wisconsin_tren_azul.png",
    top: -286.52,
    left: -252.9,
    right: -248,
    messages: [],
    errorMessages: [],
    successMessages: [],
    correctAnswer: "l",
    tutorial: false,
    item_id: null,
    answer: null,
    time: null,
  },
  {
    id: 24,
    type: "cards",
    cardOneSrc: "/images/wisconsin_tren_rojo.png",
    cardTwoSrc: "/images/wisconsin_estrella_azul.png",
    cardThreeSrc: "/images/wisconsin_estrella_roja.png",
    top: -286.52,
    left: -252.9,
    right: -248,
    messages: [],
    errorMessages: [],
    successMessages: [],
    correctAnswer: "a",
    tutorial: false,
    item_id: null,
    answer: null,
    time: null,
  },
  {
    id: 25,
    type: "cards",
    cardOneSrc: "/images/wisconsin_tren_rojo.png",
    cardTwoSrc: "/images/wisconsin_estrella_azul.png",
    cardThreeSrc: "/images/wisconsin_estrella_roja.png",
    top: -286.52,
    left: -252.9,
    right: -248,
    messages: [],
    errorMessages: [],
    successMessages: [],
    correctAnswer: "a",
    tutorial: false,
    item_id: null,
    answer: null,
    time: null,
  },
  {
    id: 26,
    type: "cards",
    cardOneSrc: "/images/wisconsin_tren_rojo.png",
    cardTwoSrc: "/images/wisconsin_estrella_azul.png",
    cardThreeSrc: "/images/wisconsin_tren_azul.png",
    top: -286.52,
    left: -252.9,
    right: -248,
    messages: [],
    errorMessages: [],
    successMessages: [],
    correctAnswer: "l",
    tutorial: false,
    item_id: null,
    answer: null,
    time: null,
  },
  {
    id: 27,
    type: "cards",
    cardOneSrc: "/images/wisconsin_tren_rojo.png",
    cardTwoSrc: "/images/wisconsin_estrella_azul.png",
    cardThreeSrc: "/images/wisconsin_tren_azul.png",
    top: -286.52,
    left: -252.9,
    right: -248,
    messages: [],
    errorMessages: [],
    successMessages: [],
    correctAnswer: "l",
    tutorial: false,
    item_id: null,
    answer: null,
    time: null,
  },
  {
    id: 28,
    type: "cards",
    cardOneSrc: "/images/wisconsin_tren_rojo.png",
    cardTwoSrc: "/images/wisconsin_estrella_azul.png",
    cardThreeSrc: "/images/wisconsin_estrella_roja.png",
    top: -286.52,
    left: -252.9,
    right: -248,
    messages: [],
    errorMessages: [],
    successMessages: [],
    correctAnswer: "a",
    tutorial: false,
    item_id: null,
    answer: null,
    time: null,
  },
  {
    id: 29,
    type: "cards",
    cardOneSrc: "/images/wisconsin_tren_rojo.png",
    cardTwoSrc: "/images/wisconsin_estrella_azul.png",
    cardThreeSrc: "/images/wisconsin_tren_azul.png",
    top: -286.52,
    left: -252.9,
    right: -248,
    messages: [],
    errorMessages: [],
    successMessages: [],
    correctAnswer: "l",
    tutorial: false,
    item_id: null,
    answer: null,
    time: null,
  },
  {
    id: 30,
    type: "cards",
    cardOneSrc: "/images/wisconsin_tren_rojo.png",
    cardTwoSrc: "/images/wisconsin_estrella_azul.png",
    cardThreeSrc: "/images/wisconsin_estrella_roja.png",
    top: -286.52,
    left: -252.9,
    right: -248,
    messages: [],
    errorMessages: [],
    successMessages: [],
    correctAnswer: "a",
    tutorial: false,
    item_id: null,
    answer: null,
    time: null,
  },
  {
    id: 31,
    type: "cards",
    cardOneSrc: "/images/wisconsin_tren_rojo.png",
    cardTwoSrc: "/images/wisconsin_estrella_azul.png",
    cardThreeSrc: "/images/wisconsin_estrella_roja.png",
    top: -286.52,
    left: -252.9,
    right: -248,
    messages: [],
    errorMessages: [],
    successMessages: [],
    correctAnswer: "a",
    tutorial: false,
    item_id: null,
    answer: null,
    time: null,
  },
  {
    id: 32,
    type: "cards",
    cardOneSrc: "/images/wisconsin_tren_rojo.png",
    cardTwoSrc: "/images/wisconsin_estrella_azul.png",
    cardThreeSrc: "/images/wisconsin_tren_azul.png",
    top: -286.52,
    left: -252.9,
    right: -248,
    messages: [],
    errorMessages: [],
    successMessages: [],
    correctAnswer: "l",
    tutorial: false,
    item_id: null,
    answer: null,
    time: null,
  },
  {
    id: 33,
    type: "cards",
    cardOneSrc: "/images/wisconsin_tren_rojo.png",
    cardTwoSrc: "/images/wisconsin_estrella_azul.png",
    cardThreeSrc: "/images/wisconsin_tren_azul.png",
    top: -286.52,
    left: -252.9,
    right: -248,
    messages: [],
    errorMessages: [],
    successMessages: [],
    correctAnswer: "l",
    tutorial: false,
    item_id: null,
    answer: null,
    time: null,
  },
  {
    id: 34,
    type: "instruction",
    instructions: ["¡Excelente trabajo! 😀"],
    specialMessage: "Toca la 'N' para continuar.",
  },
  {
    id: "35",
    type: "end"
  }
];
